### ISSUE TITLE
"Too many queries or query is too complex" issue

### ISSUE THREAD

**Issue by jmainwaring** [elementary-data/elementary#1689]
Hello! As seen in [this](https://elementary-community.slack.com/archives/C02CTC89LAX/p1715262008030929) thread, many of us continue to face the following error when run metadata is added in BigQuery:

`Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.`

I see in the thread that the issue appears to have been resolved, but I and others later in the thread are still encountering this error after upgrading to version `0.16.0`. [This](https://elementary-community.slack.com/archives/C02CTC89LAX/p1718267035194939) and [this](https://elementary-community.slack.com/archives/C02C1PLGE3T/p1724949137682069) are two other examples of users who appear to be running into the same thing. If you all have any suggestions for config changes we need to make or would be up for discussing a potential fix, that would be greatly appreciated, as there are some wonderful features in the new version that we hope to not miss out on. Thank you!

**Environment**:
Elementary dbt package version: 1.6.0
dbt version you're using: 1.7.4
Data warehouse: BigQuery

**Comment by cwmuller** [comment]
I'm also experiencing this on 0.16.0, dbt-bigquery 1.8.2. I tried setting the the query_max_size and insert_rows_method parameters, as my impression was that this was an attempt make changes that would alleviate this issue, but I am still getting the same error messages as before.

**Comment by belle-crisp** [comment]
Same for me!

**Comment by cwmuller** [comment]
Uploaded log file: [dbt.log](https://github.com/user-attachments/files/17191326/dbt.log)

**Comment by haritamar** [comment]
Hi @jmainwaring and all,

Apologies for the delayed response here. This configuration (that was mentioned in on of the threads) should probably solve this issue:
```
insert_rows_method: chunk
dbt_artifacts_chunk_size: 500
```

Some extended context about this problem - BQ has two types of limits that affect insert queries:
1. A limit on the number of rows inserted - this causes the error mentioned above.
2. A limit on the length of the entire query.
The `chunk` insert method actually handles both types of limits today, and we'll make it the default in the upcoming package release.

Thanks,
Itamar

**Comment by cwmuller** [comment]
Hi @haritamar ,

The log I posted above is the output from elementary actively failing **with** the configuration you are mentioning. Unless I have incorrectly set these parameters, they have failed to fix this issue.

**Comment by Maayan-s** [comment]
@cwmuller @belle-crisp 
@nickozilla, @benoitgoujon, @wei-wei29, @chenxilll, @kylemcleland, @neethu2409

Let us know if the config @haritamar suggested doesn't solve this 🙏🏻

**Comment by belle-crisp** [comment]
I have the same experience as @cwmuller

**Comment by haritamar** [comment]
Hi @cwmuller @belle-crisp ,
Sorry about that. 

@cwmuller another setting that might help is to tweak the `query_max_size` parameter, not sure if you did that as well. We saw in the log that the failing query has around 240K characters.
Have you tried setting `query_max_size: 100000`?

(I saw it was suggested in one of the slack thread so not sure if you tried that as well)

Itamar
Can you say if you also tried to set the `query_max_size` parameter? (the default is `1000000`, so for example to `100000`)

Thanks,
Itamar

**Comment by haritamar** [comment]
Also if you can share the full list of vars you set up would be great 🙏

**Comment by haritamar** [comment]
Hey @cwmuller ,
The configuration above is what I meant. But interesting - I think it is actually configured in the wrong place... 
These should be set as vars in `dbt_project.yml`, and not under the profiles.

e.g.:
```
vars:
  insert_rows_method: "chunk"
  dbt_artifacts_chunk_size: 500
  query_max_size: 100000
```
(I removed one zero from `query_max_size`)

If you can check if this configurations makes any difference would be great.

**Comment by cwmuller** [comment]
Hi @haritamar ,

Indeed! I moved the config from  to `vars`, and i was able to run and test the entire project, and elementary models without any failures. I had put the config under `elementary`, under `models`. I probably searched for 'elementary' in the dbt_project.yml file and added it underneath without giving it more thought.

Thanks for the assistance!

**Comment by haritamar** [comment]
That's great to hear @cwmuller !
We'll work on actually incorporating these as defaults in the next version.

**Comment by haritamar** [comment]
Hi @nickozilla !
Would you mind sharing a dbt.log file as well with this error?
Also, what is the Elementary package version you are using?

Itamar

**Comment by nickozilla** [comment]
Hi @haritamar ,

The log events I have shared are from our logs aggregator tool, so I don't have the dbt.log file accessible currently, I'll see what else I can provide, our elementary version is 0.16.0

Nick

**Comment by Niteeshkanungo** [comment]
Hello @haritamar 
I have added this as vars - 

  # elementary limits
  dbt_artifacts_chunk_size: 10000
  insert_rows_method: chunk
  query_max_size: 100000
  
I am getting - `The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.` still. DBT on BQ. 
Do we have a solution for this?

**Comment by nickozilla** [comment]
@cwmuller what were your other vars set to? & did you also experience this error?

> The query is too large. The maximum standard SQL query length is 1024.00K characters, including comments and white space characters.

**Comment by cwmuller** [comment]
@nickozilla 
You settings are:
```
  elementary:
    insert_rows_method: "chunk"
    dbt_artifacts_chunk_size: 100
    query_max_size: 1000000
```

**Comment by joostboon** [comment]
We are hoping to close this issue with the proposed solution, but please let me know if you are still experiencing this issue

@benoitgoujon @wei-wei29 @chenxilll @kylemcleland @neethu2409 @belle-crisp

**Comment by Pgillets** [comment]
Adding

vars:
    insert_rows_method: "chunk"
    dbt_artifacts_chunk_size: 1000
    query_max_size: 1000000

to the dbt_project.yaml worked for me.

**Comment by joostboon** [comment]
Thanks! That is helpful to know

**Comment by haritamar** [comment]
Hi everyone!
Some updates here.

So after a few iterations here and thanks to a contributor, we actually realized that the "chunk" method had several bugs in it, and in particular the `query_max_size` limit didn't actually work as expected. Sorry about that.
We made a refactor to the insert rows logic which I hope should solve this issue for good (crossing fingers you won't prove me otherwise 🤞 ), and released version `0.16.2` a couple of hours ago.

The `insert_rows_method` var has been removed (it won't break anything to have it but it will be ignored), and the package will take into account both the chunk size and the query max size limits.

Would love people here can try the new version and comment here how it goes (would be great if you can try it both without configuration vars, and if that doesn't work also with the limits posted above).

Thanks,
Itamar

**Comment by haritamar** [comment]
@Niteeshkanungo @amishas157 @cwmuller @nickozilla @belle-crisp @Pgillets @jmainwaring

**Comment by nickozilla** [comment]
Seems to have fixed things for us, thanks for investigating. Can you share the PR with the bugfix, out of curiosity?

**Comment by nickozilla** [comment]
@haritamar 

Small update: After some further tests without the query_max_size or dbt_artifacts_chunk_size variables set, I have found that this issue does still occur, we've settled with a stable config of:

```
  query_max_size: 1000000
  dbt_artifacts_chunk_size: 1000
```

**Comment by haritamar** [comment]
@nickozilla - Thanks for updating! This is helpful.
I think we'll lower the defaults for these values then (which are currently 1M for query size and 5000 for chunk size).

Regarding the bugfix PR - [here it is](https://github.com/elementary-data/dbt-data-reliability/pull/765)
Basically what it does is a refactor that unifies the handling of both limits to the same insert method (and as a part of it removing the `insert_rows_method` configuration).

Technically it was done by adding support for the `dbt_artifacts_chunk_size` parameter in the code that previously split the queries by query size, and removing the other insert method (which we found out was buggy and missing some features).
